export const ORDERMORE = "ORDERMORE";
export const ORDERLESS = "ORDERLESS";
export const ADDDISH = "ADDDISH";
export const ADDITEM = "ADDITEM";
export const DELETEITEM = "DELETEITEM";
export const RESTAURANT = "RESTAURANT";
export const ITEMSEARCH = "ITEMSEARCH";
export const ISAUTH = "ISAUTH";
export const ISADMIN = "ISADMIN";
export const USERPASSWORD = "USERPASSWORD";
export const USERNAME = "USERNAME";
export const SET_FORMVALUES = "SET_FORMVALUES"
// export const SUBMIT_FORM = "SUBMIT_FORM"